<script src="<?= urlOf('js/jquery-3.5.1.min.js') ?>"></script>
<script src="<?= urlOf('assets/bootstrap/js/popper.min.js') ?>"></script>
<script src="<?= urlOf('assets/bootstrap/js/bootstrap.min.js') ?>"></script>
<script src="<?= urlOf('js/pre-loader.js') ?>"></script>
<script src="<?= urlOf('assets/slick/slick.min.js') ?>"></script>
<script src="<?= urlOf('js/jquery.parallax-scroll.js') ?>"></script>
<script src="<?= urlOf('assets/niceselectpicker/jquery.nice-select.min.js') ?>"></script>
<script src="<?= urlOf('assets/wow/wow.min.js') ?>"></script>
<script src="<?= urlOf('assets/mcustomscrollbar/jquery.mCustomScrollbar.concat.min.js') ?>"></script>
<script src="<?= urlOf('assets/magnify-pop/jquery.magnific-popup.min.js') ?>"></script>
<script src="<?= urlOf('js/plugins.js') ?>"></script>
<script src="<?= urlOf('../../unpkg.com/ionicons%405.4.0/dist/ionicons.js') ?>"></script>
<script src="<?= urlOf('js/main.js') ?>"></script>